### ISSUE TITLE
Explanation Of Why A Fork of the Copilot Chat Sample Is Embedded In This Sample

### ISSUE THREAD

**Issue by karstenjMSFT** [Azure-Samples/miyagi#178]
There is no documentation that explains why a fork of the copilot chat api exists in this repo? That project is iterating quickly -- how will this one stay up to date? Also, why is it embedded in this project?

**Comment by thegovind** [comment]
I have called out that this is a fork: https://github.com/Azure-Samples/miyagi/tree/main/services/sk-copilot-chat-api/dotnet#miyagi-copilotchat-api---fork-of-sks-chat-copilot-webapi. 

I work very closely with the SK team and have made significant contributions to SK, including gRPC extensibility, in the early days. At that time, Chat-Copilot was embedded within SK as a sub-project, with dependencies to other SK projects referenced instead of nugets. Customers expressed a desire to use the Chat-Copilot backend for their own frontends—for instance, one customer implemented it in a React mobile app, and needed a reference for it. Hence, I had no option, but to "manually" clone it. Since then, Chat-Copilot has been separated into its own repository, and I have continued to update miyagi. The Chat-Copilot EM, along with core SK team, is aware of this. I opted not to include this entire story in the readme, but I can update it to clarify that the intention is to demonstrate how Chat-Copilot can be used as a backend for any frontend application.
